name: Deploy Vite React App to Cyberfolks

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build  # To uruchomi 'vite build' zgodnie z Twoim package.json
      
    - name: Deploy to Cyberfolks using SFTP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}  
        source: "build/*"
        target: "/public_html/"
   
    - name: Debug FTP connection
      run: |
        echo "Attempting to connect to FTP server..."
        ftp -n ${{ secrets.FTP_SERVER }} << EOF
        user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
        pwd
        quit
        EOF
